### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by JBocanegraGrandez** [JBocanegraGrandez/velg#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by ryan-mapa** [comment]
You need to change all references to 'velg' to 'velp' haha!

**Comment by JBocanegraGrandez** [comment]
I am using the icon of comments (bubble icon) as a log out button for now. Since I want to add modals and hopefully message functionality between users as a bonus. If I am not able to get into that on time. Then I will change the bubble button for a Log out button ( the functionality of that button as a log out is already implemented so it will be as simple as adding value of "log out" to that button)

**Comment by ryan-mapa** [comment]
- [ ] fix live off
- [ ] add error rendering (clear between login/signup)
- [ ] remove blue background

**Comment by JBocanegraGrandez** [comment]
Added  Demo Login aswell

**Comment by ryan-mapa** [comment]
Nice!
